<?php
			$optionsArray = array( 'details' => array( 'informe_intersup_oe' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'master' => array( 'q_bandejaentrada_supervisores3' => array( 'preview' => false ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'inf_numerocontrato',
'inf_doccontratista',
'inf_nombrecontratista',
'inf_hash',
'inf_fechapresenta',
'sign_hash',
'inf_dependencia',
'inf_cargo',
'inf_nombre',
'inf_intersup',
'sign_verificacert',
'inf_consecutivo',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_estado',
'sign_file' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'inf_numerocontrato' => array( 'integrated_edit_field8' ),
'inf_doccontratista' => array( 'integrated_edit_field9' ),
'inf_nombrecontratista' => array( 'integrated_edit_field10' ),
'inf_hash' => array( 'integrated_edit_field2' ),
'inf_fechapresenta' => array( 'integrated_edit_field4' ),
'sign_hash' => array( 'integrated_edit_field' ),
'inf_dependencia' => array( 'integrated_edit_field27' ),
'inf_cargo' => array( 'integrated_edit_field26' ),
'inf_nombre' => array( 'integrated_edit_field25' ),
'inf_intersup' => array( 'integrated_edit_field24' ),
'sign_verificacert' => array( 'integrated_edit_field39' ),
'inf_consecutivo' => array( 'integrated_edit_field1' ),
'inf_fecharep_i' => array( 'integrated_edit_field3' ),
'inf_fecharep_f' => array( 'integrated_edit_field5' ),
'inf_estado' => array( 'integrated_edit_field6' ),
'sign_file' => array( 'integrated_edit_field7' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'edit_header' ),
'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'grid' => array( 'tabs',
'integrated_edit_field7' ),
'section' => array( 'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field39',
'integrated_edit_field6',
'text',
'integrated_edit_field1' ),
'section2' => array( 'integrated_edit_field24',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field27' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_header' => 'top',
'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'tabs' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field3' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field39' => 'section',
'integrated_edit_field6' => 'section',
'text' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field24' => 'section2',
'integrated_edit_field25' => 'section2',
'integrated_edit_field26' => 'section2',
'integrated_edit_field27' => 'section2' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c4' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c11' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field39' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c14' ),
'text' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c16' ),
'integrated_edit_field24' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field27' => array( 'location' => 'section2',
'cellId' => 'c5' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field2',
'integrated_edit_field4',
'integrated_edit_field',
'integrated_edit_field27',
'integrated_edit_field26',
'integrated_edit_field25',
'integrated_edit_field24',
'integrated_edit_field39',
'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7' ),
'tabs' => array( 'tabs' ),
'text' => array( 'text' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c4' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs',
'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section' => array( 'cells' => array( 'c15' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5',
'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 7 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field26' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c6',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c4' => array( 'model' => 'c3',
'items' => array( 'tabs',
'integrated_edit_field7' ) ),
'c6' => array( 'model' => 'c3',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5',
'integrated_edit_field' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ),
'useFullWidth' => true ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'text' ),
'useFullWidth' => true ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c17' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c2' => array( 'model' => 'c1',
'items' => array(  ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field26' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save',
'label' => array( 'type' => 0,
'text' => 'Validar y firmar' ),
'icon' => array( 'glyph' => 'ok-sign' ),
'buttonStyle' => 'success',
'buttonSize' => 'large' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close',
'buttonStyle' => 'info',
'icon' => array( 'fa' => 'times-circle-o' ),
'buttonSize' => 'large' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field8' => array( 'field' => 'inf_numerocontrato',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'inf_doccontratista',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'inf_nombrecontratista',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'inf_hash',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'inf_fechapresenta',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field' => array( 'field' => 'sign_hash',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field27' => array( 'field' => 'inf_dependencia',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'inf_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'inf_nombre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'inf_intersup',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => '1. VERIFICA FIRMA',
'type' => 0 ),
array( 'text' => '3. SUPERVISOR',
'type' => 0 ) ),
'locations' => array( 'section',
'section2' ) ),
'integrated_edit_field39' => array( 'field' => 'sign_verificacert',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div class="alert alert-warning" role="alert">
  Escriba la clave dinámica enviada a su correo electrónico para formalizar la firma del presente informe
</div>',
'type' => 0 ) ),
'integrated_edit_field1' => array( 'field' => 'inf_consecutivo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'inf_fecharep_i',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'inf_fecharep_f',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'inf_estado',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'sign_file',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>