<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'totals' => array( 'inf_id' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'inf_consecutivo' => array( 'totalsType' => '' ),
'inf_hash' => array( 'totalsType' => '' ),
'inf_estado' => array( 'totalsType' => '' ),
'inf_fechapresenta' => array( 'totalsType' => '' ),
'inf_periodicidad' => array( 'totalsType' => '' ),
'inf_fecharep_i' => array( 'totalsType' => '' ),
'inf_fecharep_f' => array( 'totalsType' => '' ),
'inf_numerocontrato' => array( 'totalsType' => '' ),
'inf_anio' => array( 'totalsType' => '' ),
'inf_prenum' => array( 'totalsType' => '' ),
'inf_doccontratista' => array( 'totalsType' => '' ),
'inf_nombrecontratista' => array( 'totalsType' => '' ),
'inf_valorcontrato' => array( 'totalsType' => '' ),
'inf_adicionreduc' => array( 'totalsType' => '' ),
'inf_cdp' => array( 'totalsType' => '' ),
'inf_rp' => array( 'totalsType' => '' ),
'inf_rubrocode' => array( 'totalsType' => '' ),
'inf_rubroname' => array( 'totalsType' => '' ),
'inf_objeto' => array( 'totalsType' => '' ),
'inf_fechasuscripcion' => array( 'totalsType' => '' ),
'inf_fechacont_i' => array( 'totalsType' => '' ),
'inf_fechacont_f' => array( 'totalsType' => '' ),
'inf_plazo' => array( 'totalsType' => '' ),
'inf_vigencia' => array( 'totalsType' => '' ),
'inf_modificacionesplazo' => array( 'totalsType' => '' ),
'inf_intersup' => array( 'totalsType' => '' ),
'inf_nombre' => array( 'totalsType' => '' ),
'inf_cargo' => array( 'totalsType' => '' ),
'inf_dependencia' => array( 'totalsType' => '' ),
'inf_avgejecucion' => array( 'totalsType' => '' ),
'inf_actividades' => array( 'totalsType' => '' ),
'inf_declarainconf' => array( 'totalsType' => '' ),
'inf_declarainconf_obs' => array( 'totalsType' => '' ),
'inf_incumplimiento' => array( 'totalsType' => '' ),
'inf_incumplimiento_obs' => array( 'totalsType' => '' ),
'inf_otrosaspectostecnicos' => array( 'totalsType' => '' ),
'inf_recomyobserva' => array( 'totalsType' => '' ),
'file_verifica' => array( 'totalsType' => '' ),
'inf_ultimopago' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'inf_mail_a' => array( 'totalsType' => '' ),
'inf_mail_b' => array( 'totalsType' => '' ),
'url_secop' => array( 'totalsType' => '' ),
'num_poliza' => array( 'totalsType' => '' ),
'mun_ejec' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ),
'cont_modifica' => array( 'totalsType' => '' ),
'qty_inf' => array( 'totalsType' => '' ),
'qty_inf_compare' => array( 'totalsType' => '' ),
'qty_inf_verifica' => array( 'totalsType' => '' ),
'cert_mail' => array( 'totalsType' => '' ),
'cert_file' => array( 'totalsType' => '' ),
'cert_date' => array( 'totalsType' => '' ),
'cert_compare' => array( 'totalsType' => '' ),
'sign_hash' => array( 'totalsType' => '' ),
'sign_date' => array( 'totalsType' => '' ),
'sign_mailnot' => array( 'totalsType' => '' ),
'sign_verificacert' => array( 'totalsType' => '' ),
'sign_file' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_cont_fk',
'inf_consecutivo',
'inf_hash',
'inf_estado',
'inf_fechapresenta',
'inf_periodicidad',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_doccontratista',
'inf_nombrecontratista',
'inf_valorcontrato',
'inf_cdp',
'inf_rp',
'inf_rubrocode',
'inf_objeto',
'inf_fechasuscripcion',
'inf_fechacont_i',
'inf_fechacont_f',
'inf_plazo',
'inf_intersup',
'inf_nombre',
'inf_cargo',
'inf_dependencia',
'inf_avgejecucion',
'inf_actividades',
'inf_declarainconf',
'inf_declarainconf_obs',
'inf_incumplimiento',
'inf_incumplimiento_obs',
'inf_anio',
'inf_prenum',
'inf_mail_a',
'inf_mail_b',
'url_secop',
'num_poliza',
'mun_ejec',
'cont_cesion',
'cont_modifica',
'qty_inf',
'qty_inf_compare',
'qty_inf_verifica' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont_fk' => array( 'simple_grid_field1',
'simple_grid_field41' ),
'inf_consecutivo' => array( 'simple_grid_field2',
'simple_grid_field42' ),
'inf_hash' => array( 'simple_grid_field3',
'simple_grid_field43' ),
'inf_estado' => array( 'simple_grid_field4',
'simple_grid_field44' ),
'inf_fechapresenta' => array( 'simple_grid_field5',
'simple_grid_field45' ),
'inf_periodicidad' => array( 'simple_grid_field6',
'simple_grid_field46' ),
'inf_fecharep_i' => array( 'simple_grid_field7',
'simple_grid_field47' ),
'inf_fecharep_f' => array( 'simple_grid_field8',
'simple_grid_field48' ),
'inf_doccontratista' => array( 'simple_grid_field10',
'simple_grid_field49' ),
'inf_nombrecontratista' => array( 'simple_grid_field11',
'simple_grid_field50' ),
'inf_valorcontrato' => array( 'simple_grid_field12',
'simple_grid_field51' ),
'inf_cdp' => array( 'simple_grid_field14',
'simple_grid_field52' ),
'inf_rp' => array( 'simple_grid_field15',
'simple_grid_field53' ),
'inf_rubrocode' => array( 'simple_grid_field16',
'simple_grid_field54' ),
'inf_objeto' => array( 'simple_grid_field18',
'simple_grid_field55' ),
'inf_fechasuscripcion' => array( 'simple_grid_field19',
'simple_grid_field56' ),
'inf_fechacont_i' => array( 'simple_grid_field20',
'simple_grid_field57' ),
'inf_fechacont_f' => array( 'simple_grid_field21',
'simple_grid_field58' ),
'inf_plazo' => array( 'simple_grid_field22',
'simple_grid_field59' ),
'inf_intersup' => array( 'simple_grid_field25',
'simple_grid_field60' ),
'inf_nombre' => array( 'simple_grid_field26',
'simple_grid_field61' ),
'inf_cargo' => array( 'simple_grid_field27',
'simple_grid_field62' ),
'inf_dependencia' => array( 'simple_grid_field28',
'simple_grid_field63' ),
'inf_avgejecucion' => array( 'simple_grid_field30',
'simple_grid_field64' ),
'inf_actividades' => array( 'simple_grid_field31',
'simple_grid_field65' ),
'inf_declarainconf' => array( 'simple_grid_field32',
'simple_grid_field66' ),
'inf_declarainconf_obs' => array( 'simple_grid_field33',
'simple_grid_field67' ),
'inf_incumplimiento' => array( 'simple_grid_field34',
'simple_grid_field68' ),
'inf_incumplimiento_obs' => array( 'simple_grid_field35',
'simple_grid_field69' ),
'inf_anio' => array( 'simple_grid_field',
'simple_grid_field70' ),
'inf_prenum' => array( 'simple_grid_field9',
'simple_grid_field71' ),
'inf_mail_a' => array( 'simple_grid_field13',
'simple_grid_field72' ),
'inf_mail_b' => array( 'simple_grid_field17',
'simple_grid_field73' ),
'url_secop' => array( 'simple_grid_field23',
'simple_grid_field74' ),
'num_poliza' => array( 'simple_grid_field24',
'simple_grid_field75' ),
'mun_ejec' => array( 'simple_grid_field29',
'simple_grid_field76' ),
'cont_cesion' => array( 'simple_grid_field36',
'simple_grid_field77' ),
'cont_modifica' => array( 'simple_grid_field37',
'simple_grid_field78' ),
'qty_inf' => array( 'simple_grid_field38',
'simple_grid_field79' ),
'qty_inf_compare' => array( 'simple_grid_field39',
'simple_grid_field80' ),
'qty_inf_verifica' => array( 'simple_grid_field40',
'simple_grid_field81' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field41',
'simple_grid_field1',
'simple_grid_field42',
'simple_grid_field2',
'simple_grid_field43',
'simple_grid_field3',
'simple_grid_field44',
'simple_grid_field4',
'simple_grid_field45',
'simple_grid_field5',
'simple_grid_field46',
'simple_grid_field6',
'simple_grid_field47',
'simple_grid_field7',
'simple_grid_field48',
'simple_grid_field8',
'simple_grid_field49',
'simple_grid_field10',
'simple_grid_field50',
'simple_grid_field11',
'simple_grid_field51',
'simple_grid_field12',
'simple_grid_field52',
'simple_grid_field14',
'simple_grid_field53',
'simple_grid_field15',
'simple_grid_field54',
'simple_grid_field16',
'simple_grid_field55',
'simple_grid_field18',
'simple_grid_field56',
'simple_grid_field19',
'simple_grid_field57',
'simple_grid_field20',
'simple_grid_field58',
'simple_grid_field21',
'simple_grid_field59',
'simple_grid_field22',
'simple_grid_field60',
'simple_grid_field25',
'simple_grid_field61',
'simple_grid_field26',
'simple_grid_field62',
'simple_grid_field27',
'simple_grid_field63',
'simple_grid_field28',
'simple_grid_field64',
'simple_grid_field30',
'simple_grid_field65',
'simple_grid_field31',
'simple_grid_field66',
'simple_grid_field32',
'simple_grid_field67',
'simple_grid_field33',
'simple_grid_field68',
'simple_grid_field34',
'simple_grid_field69',
'simple_grid_field35',
'simple_grid_field70',
'simple_grid_field',
'simple_grid_field71',
'simple_grid_field9',
'simple_grid_field72',
'simple_grid_field13',
'simple_grid_field73',
'simple_grid_field17',
'simple_grid_field74',
'simple_grid_field23',
'simple_grid_field75',
'simple_grid_field24',
'simple_grid_field76',
'simple_grid_field29',
'simple_grid_field77',
'simple_grid_field36',
'simple_grid_field78',
'simple_grid_field37',
'simple_grid_field79',
'simple_grid_field38',
'simple_grid_field80',
'simple_grid_field39',
'simple_grid_field81',
'simple_grid_field40' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'simple_grid_field41' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field42' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field43' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field44' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field45' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field46' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field47' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field48' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field49' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field50' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field51' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field52' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field53' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field54' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field56' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field57' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field59' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field60' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field62' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field65' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field66' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field67' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field68' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field69' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field70' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field71' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field72' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field73' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field74' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field75' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field76' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field77' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field78' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field79' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field80' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field81' => 'grid',
'simple_grid_field40' => 'grid' ),
'itemLocations' => array( 'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field42' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field43' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field44' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field45' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field46' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field47' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field48' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field49' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field50' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field51' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field52' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field53' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field54' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field56' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field57' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'headcell_field17' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field59' => array( 'location' => 'grid',
'cellId' => 'headcell_field18' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'headcell_field19' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'headcell_field20' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ),
'simple_grid_field62' => array( 'location' => 'grid',
'cellId' => 'headcell_field21' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'headcell_field22' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'headcell_field23' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field65' => array( 'location' => 'grid',
'cellId' => 'headcell_field24' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field66' => array( 'location' => 'grid',
'cellId' => 'headcell_field25' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field67' => array( 'location' => 'grid',
'cellId' => 'headcell_field26' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field68' => array( 'location' => 'grid',
'cellId' => 'headcell_field27' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field69' => array( 'location' => 'grid',
'cellId' => 'headcell_field28' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_field28' ),
'simple_grid_field70' => array( 'location' => 'grid',
'cellId' => 'headcell_field29' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field29' ),
'simple_grid_field71' => array( 'location' => 'grid',
'cellId' => 'headcell_field30' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field30' ),
'simple_grid_field72' => array( 'location' => 'grid',
'cellId' => 'headcell_field31' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field31' ),
'simple_grid_field73' => array( 'location' => 'grid',
'cellId' => 'headcell_field32' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field32' ),
'simple_grid_field74' => array( 'location' => 'grid',
'cellId' => 'headcell_field33' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_field33' ),
'simple_grid_field75' => array( 'location' => 'grid',
'cellId' => 'headcell_field34' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_field34' ),
'simple_grid_field76' => array( 'location' => 'grid',
'cellId' => 'headcell_field35' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_field35' ),
'simple_grid_field77' => array( 'location' => 'grid',
'cellId' => 'headcell_field36' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_field36' ),
'simple_grid_field78' => array( 'location' => 'grid',
'cellId' => 'headcell_field37' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_field37' ),
'simple_grid_field79' => array( 'location' => 'grid',
'cellId' => 'headcell_field38' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_field38' ),
'simple_grid_field80' => array( 'location' => 'grid',
'cellId' => 'headcell_field39' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_field39' ),
'simple_grid_field81' => array( 'location' => 'grid',
'cellId' => 'headcell_field40' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_field40' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field',
'simple_grid_field9',
'simple_grid_field13',
'simple_grid_field17',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field29',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40' ),
'grid_field_label' => array( 'simple_grid_field41',
'simple_grid_field42',
'simple_grid_field43',
'simple_grid_field44',
'simple_grid_field45',
'simple_grid_field46',
'simple_grid_field47',
'simple_grid_field48',
'simple_grid_field49',
'simple_grid_field50',
'simple_grid_field51',
'simple_grid_field52',
'simple_grid_field53',
'simple_grid_field54',
'simple_grid_field55',
'simple_grid_field56',
'simple_grid_field57',
'simple_grid_field58',
'simple_grid_field59',
'simple_grid_field60',
'simple_grid_field61',
'simple_grid_field62',
'simple_grid_field63',
'simple_grid_field64',
'simple_grid_field65',
'simple_grid_field66',
'simple_grid_field67',
'simple_grid_field68',
'simple_grid_field69',
'simple_grid_field70',
'simple_grid_field71',
'simple_grid_field72',
'simple_grid_field73',
'simple_grid_field74',
'simple_grid_field75',
'simple_grid_field76',
'simple_grid_field77',
'simple_grid_field78',
'simple_grid_field79',
'simple_grid_field80',
'simple_grid_field81' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'id_cont_fk_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'inf_consecutivo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field42' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'inf_hash_fieldheadercolumn' ),
'items' => array( 'simple_grid_field43' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'inf_estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field44' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fechapresenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field45' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'inf_periodicidad_fieldheadercolumn' ),
'items' => array( 'simple_grid_field46' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fecharep_i_fieldheadercolumn' ),
'items' => array( 'simple_grid_field47' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fecharep_f_fieldheadercolumn' ),
'items' => array( 'simple_grid_field48' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'inf_doccontratista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field49' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'inf_nombrecontratista_fieldheadercolumn' ),
'items' => array( 'simple_grid_field50' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'inf_valorcontrato_fieldheadercolumn' ),
'items' => array( 'simple_grid_field51' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'inf_cdp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field52' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'inf_rp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field53' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'inf_rubrocode_fieldheadercolumn' ),
'items' => array( 'simple_grid_field54' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'inf_objeto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fechasuscripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field56' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fechacont_i_fieldheadercolumn' ),
'items' => array( 'simple_grid_field57' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fechacont_f_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 0 ),
'tags' => array( 'inf_plazo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field59' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 0 ),
'tags' => array( 'inf_intersup_fieldheadercolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 0 ),
'tags' => array( 'inf_nombre_fieldheadercolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 0 ),
'tags' => array( 'inf_cargo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field62' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 0 ),
'tags' => array( 'inf_dependencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 0 ),
'tags' => array( 'inf_avgejecucion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 0 ),
'tags' => array( 'inf_actividades_fieldheadercolumn' ),
'items' => array( 'simple_grid_field65' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 0 ),
'tags' => array( 'inf_declarainconf_fieldheadercolumn' ),
'items' => array( 'simple_grid_field66' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 0 ),
'tags' => array( 'inf_declarainconf_obs_fieldheadercolumn' ),
'items' => array( 'simple_grid_field67' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 0 ),
'tags' => array( 'inf_incumplimiento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field68' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 0 ),
'tags' => array( 'inf_incumplimiento_obs_fieldheadercolumn' ),
'items' => array( 'simple_grid_field69' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 0 ),
'tags' => array( 'inf_anio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field70' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 0 ),
'tags' => array( 'inf_prenum_fieldheadercolumn' ),
'items' => array( 'simple_grid_field71' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 0 ),
'tags' => array( 'inf_mail_a_fieldheadercolumn' ),
'items' => array( 'simple_grid_field72' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 0 ),
'tags' => array( 'inf_mail_b_fieldheadercolumn' ),
'items' => array( 'simple_grid_field73' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 0 ),
'tags' => array( 'url_secop_fieldheadercolumn' ),
'items' => array( 'simple_grid_field74' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 0 ),
'tags' => array( 'num_poliza_fieldheadercolumn' ),
'items' => array( 'simple_grid_field75' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 0 ),
'tags' => array( 'mun_ejec_fieldheadercolumn' ),
'items' => array( 'simple_grid_field76' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 0 ),
'tags' => array( 'cont_cesion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field77' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 0 ),
'tags' => array( 'cont_modifica_fieldheadercolumn' ),
'items' => array( 'simple_grid_field78' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 0 ),
'tags' => array( 'qty_inf_fieldheadercolumn' ),
'items' => array( 'simple_grid_field79' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 0 ),
'tags' => array( 'qty_inf_compare_fieldheadercolumn' ),
'items' => array( 'simple_grid_field80' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 0 ),
'tags' => array( 'qty_inf_verifica_fieldheadercolumn' ),
'items' => array( 'simple_grid_field81' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'id_cont_fk_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'inf_consecutivo_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'inf_hash_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'inf_estado_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fechapresenta_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'inf_periodicidad_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fecharep_i_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fecharep_f_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'inf_doccontratista_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'inf_nombrecontratista_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'inf_valorcontrato_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'inf_cdp_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'inf_rp_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'inf_rubrocode_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'inf_objeto_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fechasuscripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fechacont_i_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fechacont_f_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 1 ),
'tags' => array( 'inf_plazo_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 1 ),
'tags' => array( 'inf_intersup_fieldcolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 1 ),
'tags' => array( 'inf_nombre_fieldcolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 1 ),
'tags' => array( 'inf_cargo_fieldcolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 1 ),
'tags' => array( 'inf_dependencia_fieldcolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 1 ),
'tags' => array( 'inf_avgejecucion_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 1 ),
'tags' => array( 'inf_actividades_fieldcolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 1 ),
'tags' => array( 'inf_declarainconf_fieldcolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 1 ),
'tags' => array( 'inf_declarainconf_obs_fieldcolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 1 ),
'tags' => array( 'inf_incumplimiento_fieldcolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 1 ),
'tags' => array( 'inf_incumplimiento_obs_fieldcolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 1 ),
'tags' => array( 'inf_anio_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 1 ),
'tags' => array( 'inf_prenum_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 1 ),
'tags' => array( 'inf_mail_a_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 1 ),
'tags' => array( 'inf_mail_b_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 1 ),
'tags' => array( 'url_secop_fieldcolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 1 ),
'tags' => array( 'num_poliza_fieldcolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 1 ),
'tags' => array( 'mun_ejec_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 1 ),
'tags' => array( 'cont_cesion_fieldcolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 1 ),
'tags' => array( 'cont_modifica_fieldcolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 1 ),
'tags' => array( 'qty_inf_fieldcolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 1 ),
'tags' => array( 'qty_inf_compare_fieldcolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 1 ),
'tags' => array( 'qty_inf_verifica_fieldcolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field15' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field16' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field17' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field18' => array( 'cols' => array( 18 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field19' => array( 'cols' => array( 19 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field20' => array( 'cols' => array( 20 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field21' => array( 'cols' => array( 21 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field22' => array( 'cols' => array( 22 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field23' => array( 'cols' => array( 23 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field24' => array( 'cols' => array( 24 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field25' => array( 'cols' => array( 25 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field26' => array( 'cols' => array( 26 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field27' => array( 'cols' => array( 27 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field28' => array( 'cols' => array( 28 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field29' => array( 'cols' => array( 29 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field30' => array( 'cols' => array( 30 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field31' => array( 'cols' => array( 31 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field32' => array( 'cols' => array( 32 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field33' => array( 'cols' => array( 33 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field34' => array( 'cols' => array( 34 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field35' => array( 'cols' => array( 35 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field36' => array( 'cols' => array( 36 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field37' => array( 'cols' => array( 37 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field38' => array( 'cols' => array( 38 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field39' => array( 'cols' => array( 39 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field40' => array( 'cols' => array( 40 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 41,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'headcell_field18' ),
array( 'cell' => 'headcell_field19' ),
array( 'cell' => 'headcell_field20' ),
array( 'cell' => 'headcell_field21' ),
array( 'cell' => 'headcell_field22' ),
array( 'cell' => 'headcell_field23' ),
array( 'cell' => 'headcell_field24' ),
array( 'cell' => 'headcell_field25' ),
array( 'cell' => 'headcell_field26' ),
array( 'cell' => 'headcell_field27' ),
array( 'cell' => 'headcell_field28' ),
array( 'cell' => 'headcell_field29' ),
array( 'cell' => 'headcell_field30' ),
array( 'cell' => 'headcell_field31' ),
array( 'cell' => 'headcell_field32' ),
array( 'cell' => 'headcell_field33' ),
array( 'cell' => 'headcell_field34' ),
array( 'cell' => 'headcell_field35' ),
array( 'cell' => 'headcell_field36' ),
array( 'cell' => 'headcell_field37' ),
array( 'cell' => 'headcell_field38' ),
array( 'cell' => 'headcell_field39' ),
array( 'cell' => 'headcell_field40' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_field17' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field20' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27' ),
array( 'cell' => 'cell_field28' ),
array( 'cell' => 'cell_field29' ),
array( 'cell' => 'cell_field30' ),
array( 'cell' => 'cell_field31' ),
array( 'cell' => 'cell_field32' ),
array( 'cell' => 'cell_field33' ),
array( 'cell' => 'cell_field34' ),
array( 'cell' => 'cell_field35' ),
array( 'cell' => 'cell_field36' ),
array( 'cell' => 'cell_field37' ),
array( 'cell' => 'cell_field38' ),
array( 'cell' => 'cell_field39' ),
array( 'cell' => 'cell_field40' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ),
array( 'cell' => 'footcell_field15' ),
array( 'cell' => 'footcell_field16' ),
array( 'cell' => 'footcell_field17' ),
array( 'cell' => 'footcell_field18' ),
array( 'cell' => 'footcell_field19' ),
array( 'cell' => 'footcell_field20' ),
array( 'cell' => 'footcell_field21' ),
array( 'cell' => 'footcell_field22' ),
array( 'cell' => 'footcell_field23' ),
array( 'cell' => 'footcell_field24' ),
array( 'cell' => 'footcell_field25' ),
array( 'cell' => 'footcell_field26' ),
array( 'cell' => 'footcell_field27' ),
array( 'cell' => 'footcell_field28' ),
array( 'cell' => 'footcell_field29' ),
array( 'cell' => 'footcell_field30' ),
array( 'cell' => 'footcell_field31' ),
array( 'cell' => 'footcell_field32' ),
array( 'cell' => 'footcell_field33' ),
array( 'cell' => 'footcell_field34' ),
array( 'cell' => 'footcell_field35' ),
array( 'cell' => 'footcell_field36' ),
array( 'cell' => 'footcell_field37' ),
array( 'cell' => 'footcell_field38' ),
array( 'cell' => 'footcell_field39' ),
array( 'cell' => 'footcell_field40' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field41' ),
'field' => 'id_cont_fk',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'id_cont_fk',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field42' ),
'field' => 'inf_consecutivo',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'inf_consecutivo',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field43' ),
'field' => 'inf_hash',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'inf_hash',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field44' ),
'field' => 'inf_estado',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'inf_estado',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field45' ),
'field' => 'inf_fechapresenta',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'inf_fechapresenta',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field46' ),
'field' => 'inf_periodicidad',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'inf_periodicidad',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field47' ),
'field' => 'inf_fecharep_i',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'inf_fecharep_i',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field48' ),
'field' => 'inf_fecharep_f',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'inf_fecharep_f',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field49' ),
'field' => 'inf_doccontratista',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'inf_doccontratista',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field50' ),
'field' => 'inf_nombrecontratista',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'inf_nombrecontratista',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field51' ),
'field' => 'inf_valorcontrato',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'inf_valorcontrato',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field52' ),
'field' => 'inf_cdp',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'inf_cdp',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field53' ),
'field' => 'inf_rp',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'inf_rp',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field54' ),
'field' => 'inf_rubrocode',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'inf_rubrocode',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'inf_objeto',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'inf_objeto',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field56' ),
'field' => 'inf_fechasuscripcion',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'inf_fechasuscripcion',
'columnName' => 'field' ),
'footcell_field15' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field16' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field57' ),
'field' => 'inf_fechacont_i',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'inf_fechacont_i',
'columnName' => 'field' ),
'footcell_field16' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field17' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field58' ),
'field' => 'inf_fechacont_f',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'inf_fechacont_f',
'columnName' => 'field' ),
'footcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field18' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field59' ),
'field' => 'inf_plazo',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'inf_plazo',
'columnName' => 'field' ),
'footcell_field18' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field19' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'inf_intersup',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field25' ),
'field' => 'inf_intersup',
'columnName' => 'field' ),
'footcell_field19' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field20' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'inf_nombre',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field26' ),
'field' => 'inf_nombre',
'columnName' => 'field' ),
'footcell_field20' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field21' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field62' ),
'field' => 'inf_cargo',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field27' ),
'field' => 'inf_cargo',
'columnName' => 'field' ),
'footcell_field21' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field22' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field63' ),
'field' => 'inf_dependencia',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field28' ),
'field' => 'inf_dependencia',
'columnName' => 'field' ),
'footcell_field22' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field23' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field64' ),
'field' => 'inf_avgejecucion',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'inf_avgejecucion',
'columnName' => 'field' ),
'footcell_field23' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field24' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field65' ),
'field' => 'inf_actividades',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field31' ),
'field' => 'inf_actividades',
'columnName' => 'field' ),
'footcell_field24' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field25' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field66' ),
'field' => 'inf_declarainconf',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field32' ),
'field' => 'inf_declarainconf',
'columnName' => 'field' ),
'footcell_field25' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field26' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field67' ),
'field' => 'inf_declarainconf_obs',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field33' ),
'field' => 'inf_declarainconf_obs',
'columnName' => 'field' ),
'footcell_field26' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field27' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field68' ),
'field' => 'inf_incumplimiento',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field34' ),
'field' => 'inf_incumplimiento',
'columnName' => 'field' ),
'footcell_field27' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field28' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field69' ),
'field' => 'inf_incumplimiento_obs',
'columnName' => 'field' ),
'cell_field28' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field35' ),
'field' => 'inf_incumplimiento_obs',
'columnName' => 'field' ),
'footcell_field28' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field29' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field70' ),
'field' => 'inf_anio',
'columnName' => 'field' ),
'cell_field29' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'inf_anio',
'columnName' => 'field' ),
'footcell_field29' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field30' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field71' ),
'field' => 'inf_prenum',
'columnName' => 'field' ),
'cell_field30' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'inf_prenum',
'columnName' => 'field' ),
'footcell_field30' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field31' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field72' ),
'field' => 'inf_mail_a',
'columnName' => 'field' ),
'cell_field31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'inf_mail_a',
'columnName' => 'field' ),
'footcell_field31' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field32' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field73' ),
'field' => 'inf_mail_b',
'columnName' => 'field' ),
'cell_field32' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'inf_mail_b',
'columnName' => 'field' ),
'footcell_field32' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field33' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field74' ),
'field' => 'url_secop',
'columnName' => 'field' ),
'cell_field33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'url_secop',
'columnName' => 'field' ),
'footcell_field33' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field34' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field75' ),
'field' => 'num_poliza',
'columnName' => 'field' ),
'cell_field34' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'num_poliza',
'columnName' => 'field' ),
'footcell_field34' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field35' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field76' ),
'field' => 'mun_ejec',
'columnName' => 'field' ),
'cell_field35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'mun_ejec',
'columnName' => 'field' ),
'footcell_field35' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field36' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field77' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'cell_field36' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field36' ),
'field' => 'cont_cesion',
'columnName' => 'field' ),
'footcell_field36' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field37' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field78' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'cell_field37' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field37' ),
'field' => 'cont_modifica',
'columnName' => 'field' ),
'footcell_field37' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field38' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field79' ),
'field' => 'qty_inf',
'columnName' => 'field' ),
'cell_field38' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field38' ),
'field' => 'qty_inf',
'columnName' => 'field' ),
'footcell_field38' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field39' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field80' ),
'field' => 'qty_inf_compare',
'columnName' => 'field' ),
'cell_field39' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field39' ),
'field' => 'qty_inf_compare',
'columnName' => 'field' ),
'footcell_field39' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field40' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field81' ),
'field' => 'qty_inf_verifica',
'columnName' => 'field' ),
'cell_field40' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field40' ),
'field' => 'qty_inf_verifica',
'columnName' => 'field' ),
'footcell_field40' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field1' => array( 'field' => 'id_cont_fk',
'type' => 'grid_field' ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'id_cont_fk' ),
'simple_grid_field2' => array( 'field' => 'inf_consecutivo',
'type' => 'grid_field' ),
'simple_grid_field42' => array( 'type' => 'grid_field_label',
'field' => 'inf_consecutivo' ),
'simple_grid_field3' => array( 'field' => 'inf_hash',
'type' => 'grid_field' ),
'simple_grid_field43' => array( 'type' => 'grid_field_label',
'field' => 'inf_hash' ),
'simple_grid_field4' => array( 'field' => 'inf_estado',
'type' => 'grid_field' ),
'simple_grid_field44' => array( 'type' => 'grid_field_label',
'field' => 'inf_estado' ),
'simple_grid_field5' => array( 'field' => 'inf_fechapresenta',
'type' => 'grid_field' ),
'simple_grid_field45' => array( 'type' => 'grid_field_label',
'field' => 'inf_fechapresenta' ),
'simple_grid_field6' => array( 'field' => 'inf_periodicidad',
'type' => 'grid_field' ),
'simple_grid_field46' => array( 'type' => 'grid_field_label',
'field' => 'inf_periodicidad' ),
'simple_grid_field7' => array( 'field' => 'inf_fecharep_i',
'type' => 'grid_field' ),
'simple_grid_field47' => array( 'type' => 'grid_field_label',
'field' => 'inf_fecharep_i' ),
'simple_grid_field8' => array( 'field' => 'inf_fecharep_f',
'type' => 'grid_field' ),
'simple_grid_field48' => array( 'type' => 'grid_field_label',
'field' => 'inf_fecharep_f' ),
'simple_grid_field10' => array( 'field' => 'inf_doccontratista',
'type' => 'grid_field' ),
'simple_grid_field49' => array( 'type' => 'grid_field_label',
'field' => 'inf_doccontratista' ),
'simple_grid_field11' => array( 'field' => 'inf_nombrecontratista',
'type' => 'grid_field' ),
'simple_grid_field50' => array( 'type' => 'grid_field_label',
'field' => 'inf_nombrecontratista' ),
'simple_grid_field12' => array( 'field' => 'inf_valorcontrato',
'type' => 'grid_field' ),
'simple_grid_field51' => array( 'type' => 'grid_field_label',
'field' => 'inf_valorcontrato' ),
'simple_grid_field14' => array( 'field' => 'inf_cdp',
'type' => 'grid_field' ),
'simple_grid_field52' => array( 'type' => 'grid_field_label',
'field' => 'inf_cdp' ),
'simple_grid_field15' => array( 'field' => 'inf_rp',
'type' => 'grid_field' ),
'simple_grid_field53' => array( 'type' => 'grid_field_label',
'field' => 'inf_rp' ),
'simple_grid_field16' => array( 'field' => 'inf_rubrocode',
'type' => 'grid_field' ),
'simple_grid_field54' => array( 'type' => 'grid_field_label',
'field' => 'inf_rubrocode' ),
'simple_grid_field18' => array( 'field' => 'inf_objeto',
'type' => 'grid_field' ),
'simple_grid_field55' => array( 'type' => 'grid_field_label',
'field' => 'inf_objeto' ),
'simple_grid_field19' => array( 'field' => 'inf_fechasuscripcion',
'type' => 'grid_field' ),
'simple_grid_field56' => array( 'type' => 'grid_field_label',
'field' => 'inf_fechasuscripcion' ),
'simple_grid_field20' => array( 'field' => 'inf_fechacont_i',
'type' => 'grid_field' ),
'simple_grid_field57' => array( 'type' => 'grid_field_label',
'field' => 'inf_fechacont_i' ),
'simple_grid_field21' => array( 'field' => 'inf_fechacont_f',
'type' => 'grid_field' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'inf_fechacont_f' ),
'simple_grid_field22' => array( 'field' => 'inf_plazo',
'type' => 'grid_field' ),
'simple_grid_field59' => array( 'type' => 'grid_field_label',
'field' => 'inf_plazo' ),
'simple_grid_field25' => array( 'field' => 'inf_intersup',
'type' => 'grid_field' ),
'simple_grid_field60' => array( 'type' => 'grid_field_label',
'field' => 'inf_intersup' ),
'simple_grid_field26' => array( 'field' => 'inf_nombre',
'type' => 'grid_field' ),
'simple_grid_field61' => array( 'type' => 'grid_field_label',
'field' => 'inf_nombre' ),
'simple_grid_field27' => array( 'field' => 'inf_cargo',
'type' => 'grid_field' ),
'simple_grid_field62' => array( 'type' => 'grid_field_label',
'field' => 'inf_cargo' ),
'simple_grid_field28' => array( 'field' => 'inf_dependencia',
'type' => 'grid_field' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'inf_dependencia' ),
'simple_grid_field30' => array( 'field' => 'inf_avgejecucion',
'type' => 'grid_field' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'inf_avgejecucion' ),
'simple_grid_field31' => array( 'field' => 'inf_actividades',
'type' => 'grid_field' ),
'simple_grid_field65' => array( 'type' => 'grid_field_label',
'field' => 'inf_actividades' ),
'simple_grid_field32' => array( 'field' => 'inf_declarainconf',
'type' => 'grid_field' ),
'simple_grid_field66' => array( 'type' => 'grid_field_label',
'field' => 'inf_declarainconf' ),
'simple_grid_field33' => array( 'field' => 'inf_declarainconf_obs',
'type' => 'grid_field' ),
'simple_grid_field67' => array( 'type' => 'grid_field_label',
'field' => 'inf_declarainconf_obs' ),
'simple_grid_field34' => array( 'field' => 'inf_incumplimiento',
'type' => 'grid_field' ),
'simple_grid_field68' => array( 'type' => 'grid_field_label',
'field' => 'inf_incumplimiento' ),
'simple_grid_field35' => array( 'field' => 'inf_incumplimiento_obs',
'type' => 'grid_field' ),
'simple_grid_field69' => array( 'type' => 'grid_field_label',
'field' => 'inf_incumplimiento_obs' ),
'simple_grid_field' => array( 'field' => 'inf_anio',
'type' => 'grid_field' ),
'simple_grid_field70' => array( 'type' => 'grid_field_label',
'field' => 'inf_anio' ),
'simple_grid_field9' => array( 'field' => 'inf_prenum',
'type' => 'grid_field' ),
'simple_grid_field71' => array( 'type' => 'grid_field_label',
'field' => 'inf_prenum' ),
'simple_grid_field13' => array( 'field' => 'inf_mail_a',
'type' => 'grid_field' ),
'simple_grid_field72' => array( 'type' => 'grid_field_label',
'field' => 'inf_mail_a' ),
'simple_grid_field17' => array( 'field' => 'inf_mail_b',
'type' => 'grid_field' ),
'simple_grid_field73' => array( 'type' => 'grid_field_label',
'field' => 'inf_mail_b' ),
'simple_grid_field23' => array( 'field' => 'url_secop',
'type' => 'grid_field' ),
'simple_grid_field74' => array( 'type' => 'grid_field_label',
'field' => 'url_secop' ),
'simple_grid_field24' => array( 'field' => 'num_poliza',
'type' => 'grid_field' ),
'simple_grid_field75' => array( 'type' => 'grid_field_label',
'field' => 'num_poliza' ),
'simple_grid_field29' => array( 'field' => 'mun_ejec',
'type' => 'grid_field' ),
'simple_grid_field76' => array( 'type' => 'grid_field_label',
'field' => 'mun_ejec' ),
'simple_grid_field36' => array( 'field' => 'cont_cesion',
'type' => 'grid_field' ),
'simple_grid_field77' => array( 'type' => 'grid_field_label',
'field' => 'cont_cesion' ),
'simple_grid_field37' => array( 'field' => 'cont_modifica',
'type' => 'grid_field' ),
'simple_grid_field78' => array( 'type' => 'grid_field_label',
'field' => 'cont_modifica' ),
'simple_grid_field38' => array( 'field' => 'qty_inf',
'type' => 'grid_field' ),
'simple_grid_field79' => array( 'type' => 'grid_field_label',
'field' => 'qty_inf' ),
'simple_grid_field39' => array( 'field' => 'qty_inf_compare',
'type' => 'grid_field' ),
'simple_grid_field80' => array( 'type' => 'grid_field_label',
'field' => 'qty_inf_compare' ),
'simple_grid_field40' => array( 'field' => 'qty_inf_verifica',
'type' => 'grid_field' ),
'simple_grid_field81' => array( 'type' => 'grid_field_label',
'field' => 'qty_inf_verifica' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>