<?php
			$optionsArray = array( 'totals' => array( 'Fecha de Registro' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'Numero Documento' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'Rubro' => array( 'totalsType' => '' ),
'Valor Inicial' => array( 'totalsType' => '' ),
'Valor Operaciones' => array( 'totalsType' => '' ),
'Valor Actual' => array( 'totalsType' => '' ),
'Identificacion' => array( 'totalsType' => '' ),
'Nombre Razon Social' => array( 'totalsType' => '' ),
'Solicitud CDP' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'Compromisos' => array( 'totalsType' => '' ),
'Cuentas por Pagar' => array( 'totalsType' => '' ),
'Obligaciones' => array( 'totalsType' => '' ),
'Ordenes de Pago' => array( 'totalsType' => '' ),
'Tipo Cuenta' => array( 'totalsType' => '' ),
'Numero Cuenta' => array( 'totalsType' => '' ),
'Estado Cuenta' => array( 'totalsType' => '' ),
'Entidad Nit' => array( 'totalsType' => '' ),
'Entidad Descripcion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Fecha de Registro',
'vigencia',
'Numero Documento',
'Estado',
'Rubro',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Identificacion',
'Nombre Razon Social',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion' ),
'exportFields' => array( 'Fecha de Registro',
'vigencia',
'Numero Documento',
'Estado',
'Rubro',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Identificacion',
'Nombre Razon Social',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Fecha de Registro' => array( 'export_field' ),
'vigencia' => array( 'export_field1' ),
'Numero Documento' => array( 'export_field2' ),
'Estado' => array( 'export_field3' ),
'Rubro' => array( 'export_field4' ),
'Valor Inicial' => array( 'export_field5' ),
'Valor Operaciones' => array( 'export_field6' ),
'Valor Actual' => array( 'export_field7' ),
'Identificacion' => array( 'export_field8' ),
'Nombre Razon Social' => array( 'export_field9' ),
'Solicitud CDP' => array( 'export_field10' ),
'CDP' => array( 'export_field11' ),
'Compromisos' => array( 'export_field12' ),
'Cuentas por Pagar' => array( 'export_field13' ),
'Obligaciones' => array( 'export_field14' ),
'Ordenes de Pago' => array( 'export_field15' ),
'Tipo Cuenta' => array( 'export_field16' ),
'Numero Cuenta' => array( 'export_field17' ),
'Estado Cuenta' => array( 'export_field18' ),
'Entidad Nit' => array( 'export_field19' ),
'Entidad Descripcion' => array( 'export_field20' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'Fecha de Registro',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'Numero Documento',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'Estado',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'Rubro',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'Valor Inicial',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'Valor Operaciones',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'Valor Actual',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'Identificacion',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'Nombre Razon Social',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'Solicitud CDP',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'CDP',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'Compromisos',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'Cuentas por Pagar',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'Obligaciones',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'Ordenes de Pago',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'Tipo Cuenta',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'Numero Cuenta',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'Estado Cuenta',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'Entidad Nit',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'Entidad Descripcion',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>