<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Numero Documento',
'Fecha de Registro',
'vigencia',
'Estado',
'Valor Actual',
'Valor Deducciones',
'Identificacion',
'Rubro',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Objeto del Compromiso',
'Num Doc Soporte Compromiso',
'Tipo Doc Soporte Compromiso' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Numero Documento' => array( 'import_field' ),
'Fecha de Registro' => array( 'import_field1' ),
'vigencia' => array( 'import_field2' ),
'Estado' => array( 'import_field3' ),
'Valor Actual' => array( 'import_field4' ),
'Valor Deducciones' => array( 'import_field5' ),
'Identificacion' => array( 'import_field6' ),
'Rubro' => array( 'import_field7' ),
'Cuentas por Pagar' => array( 'import_field8' ),
'Obligaciones' => array( 'import_field9' ),
'Ordenes de Pago' => array( 'import_field10' ),
'Objeto del Compromiso' => array( 'import_field11' ),
'Num Doc Soporte Compromiso' => array( 'import_field12' ),
'Tipo Doc Soporte Compromiso' => array( 'import_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Numero Documento',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Fecha de Registro',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Valor Actual',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Valor Deducciones',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Identificacion',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Rubro',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Cuentas por Pagar',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Obligaciones',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Ordenes de Pago',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Objeto del Compromiso',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Num Doc Soporte Compromiso',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Tipo Doc Soporte Compromiso',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>