<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Fecha de Registro',
'vigencia',
'Numero Documento',
'Estado',
'Rubro',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Identificacion',
'Nombre Razon Social',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Fecha de Registro' => array( 'import_field' ),
'vigencia' => array( 'import_field1' ),
'Numero Documento' => array( 'import_field2' ),
'Estado' => array( 'import_field3' ),
'Rubro' => array( 'import_field4' ),
'Valor Inicial' => array( 'import_field5' ),
'Valor Operaciones' => array( 'import_field6' ),
'Valor Actual' => array( 'import_field7' ),
'Identificacion' => array( 'import_field8' ),
'Nombre Razon Social' => array( 'import_field9' ),
'Solicitud CDP' => array( 'import_field10' ),
'CDP' => array( 'import_field11' ),
'Compromisos' => array( 'import_field12' ),
'Cuentas por Pagar' => array( 'import_field13' ),
'Obligaciones' => array( 'import_field14' ),
'Ordenes de Pago' => array( 'import_field15' ),
'Tipo Cuenta' => array( 'import_field16' ),
'Numero Cuenta' => array( 'import_field17' ),
'Estado Cuenta' => array( 'import_field18' ),
'Entidad Nit' => array( 'import_field19' ),
'Entidad Descripcion' => array( 'import_field20' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Fecha de Registro',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'Numero Documento',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Rubro',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Valor Inicial',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Valor Operaciones',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Valor Actual',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'Identificacion',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Nombre Razon Social',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Solicitud CDP',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'CDP',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Compromisos',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Cuentas por Pagar',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Obligaciones',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'Ordenes de Pago',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Tipo Cuenta',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'Numero Cuenta',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'Estado Cuenta',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'Entidad Nit',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'Entidad Descripcion',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>