<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'master' => array( 'contrato' => array( 'preview' => true ) ),
'totals' => array( 'Fecha de Registro' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'Numero Documento' => array( 'totalsType' => '' ),
'Estado' => array( 'totalsType' => '' ),
'Rubro' => array( 'totalsType' => '' ),
'Valor Inicial' => array( 'totalsType' => '' ),
'Valor Operaciones' => array( 'totalsType' => '' ),
'Valor Actual' => array( 'totalsType' => '' ),
'Identificacion' => array( 'totalsType' => '' ),
'Nombre Razon Social' => array( 'totalsType' => '' ),
'Solicitud CDP' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'Compromisos' => array( 'totalsType' => '' ),
'Cuentas por Pagar' => array( 'totalsType' => '' ),
'Obligaciones' => array( 'totalsType' => '' ),
'Ordenes de Pago' => array( 'totalsType' => '' ),
'Tipo Cuenta' => array( 'totalsType' => '' ),
'Numero Cuenta' => array( 'totalsType' => '' ),
'Estado Cuenta' => array( 'totalsType' => '' ),
'Entidad Nit' => array( 'totalsType' => '' ),
'Entidad Descripcion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'Fecha de Registro',
'vigencia',
'Numero Documento',
'Estado',
'Rubro',
'Valor Inicial',
'Valor Operaciones',
'Valor Actual',
'Identificacion',
'Nombre Razon Social',
'Solicitud CDP',
'CDP',
'Compromisos',
'Cuentas por Pagar',
'Obligaciones',
'Ordenes de Pago',
'Tipo Cuenta',
'Numero Cuenta',
'Estado Cuenta',
'Entidad Nit',
'Entidad Descripcion' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Fecha de Registro' => array( 'simple_grid_field',
'simple_grid_field21' ),
'vigencia' => array( 'simple_grid_field1',
'simple_grid_field22' ),
'Numero Documento' => array( 'simple_grid_field2',
'simple_grid_field23' ),
'Estado' => array( 'simple_grid_field3',
'simple_grid_field24' ),
'Rubro' => array( 'simple_grid_field4',
'simple_grid_field25' ),
'Valor Inicial' => array( 'simple_grid_field5',
'simple_grid_field26' ),
'Valor Operaciones' => array( 'simple_grid_field6',
'simple_grid_field27' ),
'Valor Actual' => array( 'simple_grid_field7',
'simple_grid_field28' ),
'Identificacion' => array( 'simple_grid_field8',
'simple_grid_field29' ),
'Nombre Razon Social' => array( 'simple_grid_field9',
'simple_grid_field30' ),
'Solicitud CDP' => array( 'simple_grid_field10',
'simple_grid_field31' ),
'CDP' => array( 'simple_grid_field11',
'simple_grid_field32' ),
'Compromisos' => array( 'simple_grid_field12',
'simple_grid_field33' ),
'Cuentas por Pagar' => array( 'simple_grid_field13',
'simple_grid_field34' ),
'Obligaciones' => array( 'simple_grid_field14',
'simple_grid_field35' ),
'Ordenes de Pago' => array( 'simple_grid_field15',
'simple_grid_field36' ),
'Tipo Cuenta' => array( 'simple_grid_field16',
'simple_grid_field37' ),
'Numero Cuenta' => array( 'simple_grid_field17',
'simple_grid_field38' ),
'Estado Cuenta' => array( 'simple_grid_field18',
'simple_grid_field39' ),
'Entidad Nit' => array( 'simple_grid_field19',
'simple_grid_field40' ),
'Entidad Descripcion' => array( 'simple_grid_field20',
'simple_grid_field41' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader',
'master_info' ),
'above-grid' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'below-grid' => array(  ),
'grid' => array( 'simple_grid_field21',
'simple_grid_field',
'simple_grid_field28',
'simple_grid_field7',
'simple_grid_field35',
'simple_grid_field14',
'simple_grid_field22',
'simple_grid_field1',
'simple_grid_field29',
'simple_grid_field8',
'simple_grid_field36',
'simple_grid_field15',
'simple_grid_field23',
'simple_grid_field2',
'simple_grid_field30',
'simple_grid_field9',
'simple_grid_field37',
'simple_grid_field16',
'simple_grid_field24',
'simple_grid_field3',
'simple_grid_field31',
'simple_grid_field10',
'simple_grid_field38',
'simple_grid_field17',
'simple_grid_field25',
'simple_grid_field4',
'simple_grid_field32',
'simple_grid_field11',
'simple_grid_field39',
'simple_grid_field18',
'simple_grid_field26',
'simple_grid_field5',
'simple_grid_field33',
'simple_grid_field12',
'simple_grid_field40',
'simple_grid_field19',
'simple_grid_field27',
'simple_grid_field6',
'simple_grid_field34',
'simple_grid_field13',
'simple_grid_field41',
'simple_grid_field20' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages',
'inline_cancel',
'inlineadd_link' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'master_info' => 'top',
'print_pages' => 'above-grid',
'grid_inline_cancel' => 'above-grid',
'inline_add' => 'above-grid',
'simple_grid_field21' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field28' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field35' => 'grid',
'simple_grid_field14' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field36' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field37' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field38' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field25' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field39' => 'grid',
'simple_grid_field18' => 'grid',
'simple_grid_field26' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field33' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field40' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field27' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field34' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field41' => 'grid',
'simple_grid_field20' => 'grid' ),
'itemLocations' => array( 'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field28' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field35' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'simple_grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field36' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'simple_grid_field37' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'simple_grid_field38' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'simple_grid_field25' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_label13' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'simple_grid_field39' => array( 'location' => 'grid',
'cellId' => 'cell_label14' ),
'simple_grid_field18' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'simple_grid_field26' => array( 'location' => 'grid',
'cellId' => 'cell_label15' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'simple_grid_field33' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'simple_grid_field40' => array( 'location' => 'grid',
'cellId' => 'cell_label17' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_field17' ),
'simple_grid_field27' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field34' => array( 'location' => 'grid',
'cellId' => 'cell_label19' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field41' => array( 'location' => 'grid',
'cellId' => 'cell_label20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_field20' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field13',
'simple_grid_field14',
'simple_grid_field15',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field18',
'simple_grid_field19',
'simple_grid_field20' ),
'master_info' => array( 'master_info' ),
'grid_field_label' => array( 'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field23',
'simple_grid_field24',
'simple_grid_field25',
'simple_grid_field26',
'simple_grid_field27',
'simple_grid_field28',
'simple_grid_field29',
'simple_grid_field30',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field33',
'simple_grid_field34',
'simple_grid_field35',
'simple_grid_field36',
'simple_grid_field37',
'simple_grid_field38',
'simple_grid_field39',
'simple_grid_field40',
'simple_grid_field41' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_de_Registro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'Fecha_de_Registro_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Actual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field28' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'Valor_Actual_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'Obligaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field35' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'Obligaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'vigencia_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'vigencia_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'Identificacion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'Identificacion_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array( 'Ordenes_de_Pago_fieldheadercolumn' ),
'items' => array( 'simple_grid_field36' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array( 'Ordenes_de_Pago_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'Numero_Documento_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'Numero_Documento_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'Nombre_Razon_Social_fieldheadercolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'Nombre_Razon_Social_fieldcolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array( 'Tipo_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field37' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array( 'Tipo_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'Estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'Estado_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'Solicitud_CDP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'Solicitud_CDP_fieldcolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 4 ),
'rows' => array( 4 ),
'tags' => array( 'Numero_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field38' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 5 ),
'rows' => array( 4 ),
'tags' => array( 'Numero_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'Rubro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field25' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'Rubro_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label13' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'CDP_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'CDP_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label14' => array( 'cols' => array( 4 ),
'rows' => array( 5 ),
'tags' => array( 'Estado_Cuenta_fieldheadercolumn' ),
'items' => array( 'simple_grid_field39' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 5 ),
'rows' => array( 5 ),
'tags' => array( 'Estado_Cuenta_fieldcolumn' ),
'items' => array( 'simple_grid_field18' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'Valor_Inicial_fieldheadercolumn' ),
'items' => array( 'simple_grid_field26' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'Valor_Inicial_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array( 'Compromisos_fieldheadercolumn' ),
'items' => array( 'simple_grid_field33' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'Compromisos_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 4 ),
'rows' => array( 6 ),
'tags' => array( 'Entidad_Nit_fieldheadercolumn' ),
'items' => array( 'simple_grid_field40' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 5 ),
'rows' => array( 6 ),
'tags' => array( 'Entidad_Nit_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'Valor_Operaciones_fieldheadercolumn' ),
'items' => array( 'simple_grid_field27' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'Valor_Operaciones_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label19' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array( 'Cuentas_por_Pagar_fieldheadercolumn' ),
'items' => array( 'simple_grid_field34' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'Cuentas_por_Pagar_fieldcolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label20' => array( 'cols' => array( 4 ),
'rows' => array( 7 ),
'tags' => array( 'Entidad_Descripcion_fieldheadercolumn' ),
'items' => array( 'simple_grid_field41' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field20' => array( 'cols' => array( 5 ),
'rows' => array( 7 ),
'tags' => array( 'Entidad_Descripcion_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 6,
'height' => 9 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c4' => array( 'model' => 'c4',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages',
'grid_inline_cancel',
'inline_add' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 6 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_label13' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_label14' ),
array( 'cell' => 'cell_field14' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field15' ),
array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field17' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label18' ),
array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_label19' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_label20' ),
array( 'cell' => 'cell_field20' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 6 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field21' ),
'field' => 'Fecha de Registro',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'Fecha de Registro',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field28' ),
'field' => 'Valor Actual',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'Valor Actual',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field35' ),
'field' => 'Obligaciones',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field14' ),
'field' => 'Obligaciones',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field22' ),
'field' => 'vigencia',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'vigencia',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field29' ),
'field' => 'Identificacion',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'Identificacion',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field36' ),
'field' => 'Ordenes de Pago',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'Ordenes de Pago',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field23' ),
'field' => 'Numero Documento',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Numero Documento',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field30' ),
'field' => 'Nombre Razon Social',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'Nombre Razon Social',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field37' ),
'field' => 'Tipo Cuenta',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field16' ),
'field' => 'Tipo Cuenta',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field24' ),
'field' => 'Estado',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'Estado',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field31' ),
'field' => 'Solicitud CDP',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'Solicitud CDP',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field38' ),
'field' => 'Numero Cuenta',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field17' ),
'field' => 'Numero Cuenta',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field25' ),
'field' => 'Rubro',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'Rubro',
'columnName' => 'field' ),
'cell_label13' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field32' ),
'field' => 'CDP',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'CDP',
'columnName' => 'field' ),
'cell_label14' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field39' ),
'field' => 'Estado Cuenta',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field18' ),
'field' => 'Estado Cuenta',
'columnName' => 'field' ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field26' ),
'field' => 'Valor Inicial',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'Valor Inicial',
'columnName' => 'field' ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field33' ),
'field' => 'Compromisos',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'Compromisos',
'columnName' => 'field' ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field40' ),
'field' => 'Entidad Nit',
'columnName' => 'field' ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'Entidad Nit',
'columnName' => 'field' ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field27' ),
'field' => 'Valor Operaciones',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'Valor Operaciones',
'columnName' => 'field' ),
'cell_label19' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field34' ),
'field' => 'Cuentas por Pagar',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'Cuentas por Pagar',
'columnName' => 'field' ),
'cell_label20' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field41' ),
'field' => 'Entidad Descripcion',
'columnName' => 'field' ),
'cell_field20' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'Entidad Descripcion',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 3 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'simple_grid_field' => array( 'field' => 'Fecha de Registro',
'type' => 'grid_field' ),
'simple_grid_field1' => array( 'field' => 'vigencia',
'type' => 'grid_field' ),
'simple_grid_field2' => array( 'field' => 'Numero Documento',
'type' => 'grid_field' ),
'simple_grid_field3' => array( 'field' => 'Estado',
'type' => 'grid_field' ),
'simple_grid_field4' => array( 'field' => 'Rubro',
'type' => 'grid_field' ),
'simple_grid_field5' => array( 'field' => 'Valor Inicial',
'type' => 'grid_field' ),
'simple_grid_field6' => array( 'field' => 'Valor Operaciones',
'type' => 'grid_field' ),
'simple_grid_field7' => array( 'field' => 'Valor Actual',
'type' => 'grid_field' ),
'simple_grid_field8' => array( 'field' => 'Identificacion',
'type' => 'grid_field' ),
'simple_grid_field9' => array( 'field' => 'Nombre Razon Social',
'type' => 'grid_field' ),
'simple_grid_field10' => array( 'field' => 'Solicitud CDP',
'type' => 'grid_field' ),
'simple_grid_field11' => array( 'field' => 'CDP',
'type' => 'grid_field' ),
'simple_grid_field12' => array( 'field' => 'Compromisos',
'type' => 'grid_field' ),
'simple_grid_field13' => array( 'field' => 'Cuentas por Pagar',
'type' => 'grid_field' ),
'simple_grid_field14' => array( 'field' => 'Obligaciones',
'type' => 'grid_field' ),
'simple_grid_field15' => array( 'field' => 'Ordenes de Pago',
'type' => 'grid_field' ),
'simple_grid_field16' => array( 'field' => 'Tipo Cuenta',
'type' => 'grid_field' ),
'simple_grid_field17' => array( 'field' => 'Numero Cuenta',
'type' => 'grid_field' ),
'simple_grid_field18' => array( 'field' => 'Estado Cuenta',
'type' => 'grid_field' ),
'simple_grid_field19' => array( 'field' => 'Entidad Nit',
'type' => 'grid_field' ),
'simple_grid_field20' => array( 'field' => 'Entidad Descripcion',
'type' => 'grid_field' ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'contrato' => 'true' ) ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'Fecha de Registro' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'vigencia' ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'Numero Documento' ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'Estado' ),
'simple_grid_field25' => array( 'type' => 'grid_field_label',
'field' => 'Rubro' ),
'simple_grid_field26' => array( 'type' => 'grid_field_label',
'field' => 'Valor Inicial' ),
'simple_grid_field27' => array( 'type' => 'grid_field_label',
'field' => 'Valor Operaciones' ),
'simple_grid_field28' => array( 'type' => 'grid_field_label',
'field' => 'Valor Actual' ),
'simple_grid_field29' => array( 'type' => 'grid_field_label',
'field' => 'Identificacion' ),
'simple_grid_field30' => array( 'type' => 'grid_field_label',
'field' => 'Nombre Razon Social' ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'Solicitud CDP' ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'CDP' ),
'simple_grid_field33' => array( 'type' => 'grid_field_label',
'field' => 'Compromisos' ),
'simple_grid_field34' => array( 'type' => 'grid_field_label',
'field' => 'Cuentas por Pagar' ),
'simple_grid_field35' => array( 'type' => 'grid_field_label',
'field' => 'Obligaciones' ),
'simple_grid_field36' => array( 'type' => 'grid_field_label',
'field' => 'Ordenes de Pago' ),
'simple_grid_field37' => array( 'type' => 'grid_field_label',
'field' => 'Tipo Cuenta' ),
'simple_grid_field38' => array( 'type' => 'grid_field_label',
'field' => 'Numero Cuenta' ),
'simple_grid_field39' => array( 'type' => 'grid_field_label',
'field' => 'Estado Cuenta' ),
'simple_grid_field40' => array( 'type' => 'grid_field_label',
'field' => 'Entidad Nit' ),
'simple_grid_field41' => array( 'type' => 'grid_field_label',
'field' => 'Entidad Descripcion' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>